### ISSUE TITLE
PasswordInput 和  TextInput 加背景色后组件容器背景色不对

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [hjfruit/react-native-xiaoshu#28]
![image](https://user-images.githubusercontent.com/25316619/215933427-d402bdb3-fb0a-4057-842a-5a11b15379fe.png)
![image](https://user-images.githubusercontent.com/25316619/215933475-805a825d-93a9-4159-96bd-bd7dfafd77bd.png)
 tabs组件的分割线颜色是否可以自定义颜色？
![image](https://user-images.githubusercontent.com/25316619/215933611-57d305fa-a097-493c-90fb-7b6447c50238.png)

**Comment by onlyling** [comment]
TextInput、PasswordInput 添加 `bodered` 属性后布局（嵌套层级）有比较大的变化，通过 `fixGroupStyle` 修改背景色。
具体元素层级参考文档 [元素结构](https://hjfruit.github.io/xiaoshu-doc/component/form/text-input#%E5%85%83%E7%B4%A0%E7%BB%93%E6%9E%84)。

**Comment by onlyling** [comment]
`Tabs` 已添加 `dividerColor` 属性自定义分割线颜色。
