### ISSUE TITLE
Tree组件中,节点能否添加拓展

### ISSUE THREAD

**Issue by WangShayne** [hjfruit/react-native-xiaoshu#32]
如在非叶子节点中新建子节点,删除节点等

**Comment by onlyling** [comment]
目前可以尝试 `options` 每个对象使用 `render` 添加额外元素。
https://github.com/hjfruit/react-native-xiaoshu/blob/main/src/tree/tree-item.tsx#L82

**Comment by WangShayne** [comment]
可用,谢谢
