### ISSUE TITLE
Switch 的选项可以自定义吗？常规是布尔类型，可以自定义数字1和0或者字符串1和0吗

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [hjfruit/react-native-xiaoshu#35]
Switch 的选项可以自定义吗？常规是布尔类型，可以自定义数字1和0或者字符串1和0吗

**Comment by onlyling** [comment]
```tsx
const Demo = () => {
  return (
   // 泛型1 打开时对应的类型
   // 泛型2 关闭时对应的类型
   // 相对简单的数据会自动推导出来的，如果涉及特定值最好手动声明一下
    <Switch<string, string>
      value="打开时对应的值或关闭时对应的值"
      activeValue="打开时对应的值"
      inactiveValue="关闭时对应的值"
    />
  );
};

```

**Comment by jiaoxiaoyuan** [comment]
好的，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LING_ZI_QING ***@***.***&gt;
发送时间: 2023年9月28日 13:41
收件人: hjfruit/react-native-xiaoshu ***@***.***&gt;
抄送: NativeBase ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hjfruit/react-native-xiaoshu] Switch 的选项可以自定义吗？常规是布尔类型，可以自定义数字1和0或者字符串1和0吗 (Issue #35)





 const Demo = () =&gt; {   return (    // 泛型1 打开时对应的类型    // 泛型2 关闭时对应的类型    // 相对简单的数据会自动推导出来的，如果涉及特定值最好手动声明一下     <Switch<string, string&gt;       value="打开时对应的值或关闭时对应的值"       activeValue="打开时对应的值"       inactiveValue="关闭时对应的值"     /&gt;   ); };
