### ISSUE TITLE
Form里面使用Field.Date能否在组件上现实的自定义时间格式？

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [hjfruit/react-native-xiaoshu#36]
Form里面使用Field.Date能否在组件上现实的自定义时间格式？formatValueText仅仅只是页面，但提交还是默认的格式。如Vue中UI组件element-plus里面DatePicker日期选择器中el-date-picker组件里面的format自定义时间格式效果。

**Comment by jiaoxiaoyuan** [comment]
Form里面使用Field.Date能否在组件上现实的自定义时间格式？formatValueText仅仅只是页面，但提交还是默认的格式。如Vue中UI组件element-plus里面DatePicker日期选择器中el-date-picker组件里面的format自定义时间格式效果。

**Comment by onlyling** [comment]
应该实现不了。

`Field.Date` 等具备格式化操作的组件，仅仅在显示的时候操作一下，本身保存的值并没有改变。
`Form.Item` 组件是在子组件的 `value`、`onChange` 属性上做了一些包裹，本身并不操作子组件。如果想要在 `form.submit` 做格式化，就需要 `Form.Item` 对子组件的 `props` 检测、收集格式化操作，操作起来就会有点复杂。

**Comment by jiaoxiaoyuan** [comment]
那么修改渲染的时间格式吗？比如后端给的是一个时间，但是咱们这个组件识别的好像只能是中国标准时间格式

**Comment by onlyling** [comment]
时间选择器的值是 `Date` 类型，按理说是使用的客户端本地的时区。

**Comment by jiaoxiaoyuan** [comment]
Switch 开关 组件可以实现，如下图片所示的效果吗？
![image](https://github.com/hjfruit/react-native-xiaoshu/assets/25316619/041e72c7-a306-4360-aeae-ee78ca2117f7)

**Comment by jiaoxiaoyuan** [comment]
https://cloud.githubusercontent.com/assets/13334788/19770557/c1d935ee-9c70-11e6-931e-8812fbe62774.gif

**Comment by onlyling** [comment]
> https://cloud.githubusercontent.com/assets/13334788/19770557/c1d935ee-9c70-11e6-931e-8812fbe62774.gif

当前还能在控件内部添加文案，后面可以参考 [Antd Switch 开关](https://ant.design/components/switch-cn#switch-demo-text) 实现。

**Comment by onlyling** [comment]
> Switch 开关 组件可以实现，如下图片所示的效果吗？ ![image](https://user-images.githubusercontent.com/25316619/277112651-041e72c7-a306-4360-aeae-ee78ca2117f7.png)

`0.3.17-beta.8` 可以通过 `activeChildren`、`inactiveChildren`。
查看 [文字和图标](https://hjfruit.github.io/xiaoshu-doc/component/form/switch/#__fixtures__-text-1)。

**Comment by jiaoxiaoyuan** [comment]
好的，非常感谢！
