### ISSUE TITLE
表单里面的placeholder字体大小可以改吗？

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [hjfruit/react-native-xiaoshu#38]
表单里面的各个组件的placeholder字体大小可以改吗？

**Comment by onlyling** [comment]
- `Field.TextInput`、`Field.NumberInput` 添加 `textInputStyle`，fontSize 可以修改，同时输入的内容文字也会被影响
- `Field.Selector`、`Field.Date`、`Field.DateRange` 添加 `valueTextStyle`，fontSize 可以修改，同时选择后的文案文字也会被影响

**Comment by jiaoxiaoyuan** [comment]
感谢
