### ISSUE TITLE
Toast，Notify这些提示类的组件没有效果

### ISSUE THREAD

**Issue by Howie7793** [hjfruit/react-native-xiaoshu#45]
很好的组件库，不过遇到一个小问题，form button这些组件都可以正常用的，但是Toast，Notify这些提示类的组件没有效果，也没报错，是按照文档中进行的起步操作。

**Comment by onlyling** [comment]
有没有在根节点套一个 `Provider` 呢？

**Comment by Howie7793** [comment]
是的，谢谢已解决，我是一个新手，在根节点套一个Provider就可以了。
