### ISSUE TITLE
Field.TextInput 标签使用vertical上下排列的时候，单位没有了

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [hjfruit/react-native-xiaoshu#46]
![image](https://github.com/hjfruit/react-native-xiaoshu/assets/25316619/cac0e78c-427f-45c8-9bfb-4ae2692ef4e4)
![image](https://github.com/hjfruit/react-native-xiaoshu/assets/25316619/5cfb4ddc-2e8d-4000-bc88-bedd48e5986f)

**Comment by onlyling** [comment]
在代码实现中，如果是竖向排版，Field.TextInput 就会更改为 `textarea` [代码](https://github.com/hjfruit/react-native-xiaoshu/blob/main/src/field/field-text-input.tsx#L28)，在 TextInput 中，如果是 `textarea` 就不会有 addonBefore、addonAfter、prefix、suffix [代码](https://github.com/hjfruit/react-native-xiaoshu/blob/main/src/text-input/text-input.tsx#L236)。

**Comment by jiaoxiaoyuan** [comment]
就这个功能如需要实现，咱们这面团队好处理吗？

**Comment by onlyling** [comment]
可以使用 Cell 和 TextInput 组合一下。

<img width="374" alt="image" src="https://github.com/hjfruit/react-native-xiaoshu/assets/9999765/8e2cec47-a1a8-4bdc-a301-46bfad62a49d">

```jsx
<Cell
  title="标题"
  vertical
  value={<TextInput placeholder="请输入" bordered addonAfter="天" />}
/>
```
