### ISSUE TITLE
启动工程的时候报错

### ISSUE THREAD

**Issue by geeker-cmc** [hjfruit/react-native-xiaoshu#48]
invalid hook call.hooks can only be called inside of the body of a function component.
package.json信息
{
  "name": "Test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.1",
    "@fruits-chain/react-native-xiaoshu": "0.3.18",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/native-stack": "6.9.17",
    "axios": "1.6.2",
    "rc-field-form": "1.41.0",
    "react-native-gesture-handler": "2.14.0",
    "react-native-root-siblings": "5.0.1",
    "react-native-root-toast": "3.5.1",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "3.27.0",
    "react-native-svg": "14.1.0",
    "zustand": "4.4.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "^0.73.18",
    "@react-native/eslint-config": "^0.73.1",
    "@react-native/metro-config": "^0.73.2",
    "@react-native/typescript-config": "^0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
使用Provider就直接报上面的错。
node版本20.10.0
系统mac m2

**Comment by onlyling** [comment]
```bash
npx react-native init Restore

## 删除 node_modules、lock 文件
## dependencies 按照上面的贴进去

yarn

cd ios
pod install

yarn ios
```

没有报错诶，Android 端没有试，JDK 版本和 React Native 0.73.x 要求的不一致。

<img width="1428" alt="image" src="https://github.com/hjfruit/react-native-xiaoshu/assets/9999765/b9324cdb-0e2e-48df-b8a1-434c0d7d8b42">

**Comment by geeker-cmc** [comment]
嗯，使用yarn安装是正常的，使用npm安装就会报上述的问题，不知道是什么原因。

**Comment by geeker-cmc** [comment]
> ```shell
> npx react-native init Restore
> 
> ## 删除 node_modules、lock 文件
> ## dependencies 按照上面的贴进去
> 
> yarn
> 
> cd ios
> pod install
> 
> yarn ios
> ```
> 
> node -v v18.19.0
> 
> 没有报错诶，Android 端没有试，JDK 版本和 React Native 0.73.x 要求的不一致。
> 
> <img alt="image" width="1428" src="https://private-user-images.githubusercontent.com/9999765/292802699-b9324cdb-0e2e-48df-b8a1-434c0d7d8b42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjgxMjQsIm5iZiI6MTcwMzU2NzgyNCwicGF0aCI6Ii85OTk5NzY1LzI5MjgwMjY5OS1iOTMyNGNkYi0wZTJlLTQ4ZGYtYjhhMS00MzRjMGQ3ZDhiNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDUxNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVmZDQ4NWNjMzJlNGU0Y2I5OWM5ZjMwYjgzNWNkNDBlMjU3YzliNzdjZWNmNmI5Nzc4YjA1MGNkMjc1NjU4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yS74sDjYYTxaBhj5uKgqUftiUpC-hvNjAS0ynNMIIwA">

**Comment by onlyling** [comment]
> 嗯，使用yarn安装是正常的，使用npm安装就会报上述的问题，不知道是什么原因。

之前用 Expo 还原问题用 NPM 的方式也遇见过问题，当时是在 `node_modules/@fruits-chain/react-native-xiaoshu` 路径下安装了一份不同版本的 React Native，可能是一些依赖库对 React Native 版本锁定了，NPM 没有把依赖拍平。
