### ISSUE TITLE
Tree组件 

### ISSUE THREAD

**Issue by qianshihoushi** [hjfruit/react-native-xiaoshu#54]
如何可以不点击Tree组件的icon来进行节点的展开，能点击文字展开节点吗？

**Comment by onlyling** [comment]
暂时做不到，原因是逻辑判断比较麻烦。

点击文字是选中还是展开收起？
- 单/多选 只能选择子节点，点击文字展开收起问题不大。
- 单/多选 任意节点都能选择，选中还是展开收起呢？

如果把这个判断逻辑抛给业务方实现，组件内部就变的比较复杂。Antd 桌面端有 [目录](https://ant.design/components/tree-cn#components-tree-demo-directory) 案例实现了点击文字展开，多选需要通过键盘按键兼容，在手机上暂时不好实现。
