### ISSUE TITLE
Overlay 遮罩层 组件问题

### ISSUE THREAD

**Issue by qianshihoushi** [hjfruit/react-native-xiaoshu#55]
在使用Overlay组件的时候，在Overlay组件内部中有上下滑动的需要，使用ScrollView，FlatList的时候，滑动的时候没有反应。

**Comment by onlyling** [comment]
> 外层嵌套 TouchableWithoutFeedback，可以阻断子元素的点击事件向外传递，避免误触发关闭。一般情况不在内部放置子元素，而是和其他弹出层同层级。

可能是这个原因导致手势交互出现问题。

**Comment by qianshihoushi** [comment]
> > 外层嵌套 TouchableWithoutFeedback，可以阻断子元素的点击事件向外传递，避免误触发关闭。一般情况不在内部放置子元素，而是和其他弹出层同层级。
> 
> 可能是这个原因导致手势交互出现问题。

我试过把这个TouchableWithoutFeedback这个组件去掉，只在Overlay中嵌套一个View，使用ScrollView，FlatList，也是滑动不了的。

**Comment by onlyling** [comment]
在 `Overlay` 内部还有一个 `TouchableOpacity` 把子组件包裹，[代码](https://github.com/hjfruit/react-native-xiaoshu/blob/main/src/overlay/overlay.tsx#L113)，更适合使用 `Popup.Page` 套 `ScrollView`，[案例](https://hjfruit.github.io/xiaoshu-doc/component/basic/popup#__fixtures__-page)。

**Comment by qianshihoushi** [comment]
> 在 `Overlay` 内部还有一个 `TouchableOpacity` 把子组件包裹，[代码](https://github.com/hjfruit/react-native-xiaoshu/blob/main/src/overlay/overlay.tsx#L113)，更适合使用 `Popup.Page` 套 `ScrollView`，[案例](https://hjfruit.github.io/xiaoshu-doc/component/basic/popup#__fixtures__-page)。

好的，麻烦了。
